services:
  yisu_hotel_booking_backend:
    image: node:24
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@yisu_hotel_booking_db:5432/yisu_hotel_booking
    depends_on:
      - yisu_hotel_booking_db
    networks:
      - hotel-network
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run start:dev
    restart: unless-stopped

  yisu_hotel_booking_db:
    image: postgis/postgis:15-3.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yisu_hotel_booking
      - TZ=Asia/Shanghai
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - hotel-network
    restart: unless-stopped

networks:
  hotel-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
